language: shell

before_install:
- eval "${MATRIX_EVAL}"

matrix:
  include:
  - name: Linux Clang Build
    os: linux
    dist: xenial
    env:
    - CC=clang CXX=clang++
    addons:
      apt:
        packages:
        - cmake
        - libpci3
        - libpci-dev
    before_script:
    - mkdir build && cd build
    script:
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
  - name: Windows Clang Build (Release)
    os: windows
    env:
    - CC="/c/Program Files/LLVM/bin/clang" CXX="/c/Program Files/LLVM/bin/clang++"
    install:
    # MSVC is already installed on Travis, keep it here just in case we need to use it later
    #- choco install visualstudio2017-workload-vctools -y --package-parameters "--no-includeRecommended --add Microsoft.VisualStudio.Component.VC.x86.amd64 --add Microsoft.VisualStudio.Component.Windows10SDK"
    - choco install make
    - choco upgrade llvm -y
    - |-
      "${CC}" --version
    before_script:
    - mkdir build && cd build
    script:
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
    - cd ..
    after_success:
    - 7z.exe a -tzip ryzenadj-win64-release.zip ./build/ryzenadj.exe ./prebuilt/WinRing0x64.dll
      ./prebuilt/WinRing0x64.sys ./prebuilt/demo.bat
    - 7z.exe a -tzip libryzenadj-win64-release.zip ./build/libryzenadj.dll ./build/libryzenadj.lib
      ./prebuilt/WinRing0x64.dll ./prebuilt/WinRing0x64.sys ./lib/ryzenadj.h
    deploy:
      provider: releases
      api_key:
        secure: ejG/jwocBa+IRxt/pexN2yiDxETVhn86mfOif3aISLOdalMVoDS6ZhvBbS4TppOBBf6iUSJc4SuWfqDAulvNHCjzWNYIW1YvAg95t86Rvi6fSbSWIbpW3BQhWBt0wzkbko+/Q2kQ0lBGlAZfsSD1UHpUvnHJUWRaKJvD1wqoGpv67kDh067eBa0/SqRhVdrjuTzjRhzqig8nhv1lkDx+Nm4oRtmCEOhrNLJhovogZphppzUaRcVNE1hZmVgQjt2nD7GcyrTYIqWDOdxc/G/outM993B3j0lO+1o1sPeGGTwH0AZuYoD2fVnRvBlADWVvn0ZBUStLiJ8d3eqTJw9S7XQpJAucOTJfiPBGgp4Z53+F/FhMue+0gHnw1lWuW917+AU+VlDHDESr//SrXl1qQCfCnd4yKAvscebXQwpacF1WW3VdAhelQsd7xHcPD9e48wOKPbUY/MBGXOZJkVux5H3X6NE736xuNF23yldnVhSkr8+BTmjwKB/rwg8g0OdNoqOrI3FWKA6HS3lsqXVAbpmUZchDuoz+fLgxByZA2SPG8I3u7yggiRy7taGIQ+lYRnzLwF233/VfiftdvIVtdOwBJphedwWUUxtkfBi5W8r8BeMVe9U+sgHLHoQim7DEawNJ9Fj95oszoVC2DVChQgzc5lDTnMySmvASFIQzD7k=
      file:
      - ryzenadj-win64-release.zip
      - libryzenadj-win64-release.zip
      skip_cleanup: true
      draft: true
      on:
        tags: true
      repo: FlyGoat/RyzenAdj
